export const home = "/"
export const chamados = "/chamados"
export const abrirChamado = "/abrirChamado"
export const login = "/login"
export const cadastro = "/cadastro"
export const cadastroCliente = "/cadastroCliente"
export const cadastroSuporte = "/cadastroSuporte"
export const entrar = "/entrar"
export const FAQ = "/FAQ"
export const opcaoCadastro = "/opcaoCadastro"
export const alterarDados = "/alterarDados"
export const contato = "/contato"
export const chamadoAberto = "/chamadoAberto"
export const notFound = "/notFound"
export const cliente = "/cliente"
export const chamadosSuporte = "/chamadosSuporte"
export const admin = "/admin"

