export const home = "/"
export const chamados = "/chamados"
export const abrirChamado = "/abrirChamado"
export const login = "/login"
export const cadastro = "/cadastro"
export const cadastrar = "/cadastroopcao"
export const notFound = "/notFound"